# workflows:
#   my-workflow:
#     name: Meal App
    
#     instance_type: mac_mini
#     max_build_duration: 60
#     environment:
#       groups:
#         - mealapp
#       vars:
#         app_name: "value here"
workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      # android_signing:
      #   - keystore_reference
      groups:
        - mealapp
      vars:
        PACKAGE_NAME: "com.mohammad_azeem.foodapp"
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: | 
          npm install --legacy-peer-deps
      # - name: Install Expo CLI and eject
      #   script: | 
      #     npm install -g expo-cli
      #     expo eject
      # - name: Set up app/build.gradle
      #   script: | 
      #     mv ./support-files/build.gradle android/app
      
          
         # react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
WEBHOOKURL=${API_URL}
      curl -H 'Content-Type: application/json' -d '{"tenant_id": "'"2222"'","status": "success","build_id": "'"5126312314"'","output_url": "'"www.onlinekaka.com"'"}' "$API_URL")  
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - azeemmohammad377@gmail.com
          - apps@hyperzod.com
          
             

        notify:
          success: true
          failure: false