workflows:
  hello-world:
    name: Hello world workflow
    scripts:
      - name: Set post response
        script: |
        
          curl --insecure -X POST -f -d '{"status":"success"}' -H 'Content-Type: application/json' \
            https://webhook.site/19df8399-88bb-4923-b530-983a317a93e2
    publishing:
      email:
        recipients:
          - azeemmohammad377@gmail.com
          - apps@hyperzod.com
        notify:
          success: true
          failure: false
