workflows:
  hello-world:
    name: Hello world workflow
    scripts:
      - name: Set post response
        script: |
        
          curl --insecure -X POST -f -d '{"status":"success"}' -H 'Content-Type: application/json' \
            https://webhook.site/8c30083b-c584-4b6c-a97b-6e8802906609
    publishing:
      email:
        recipients:
          - azeemmohammad377@gmail.com
          - apps@hyperzod.com
        notify:
          success: true
          failure: false
